ROOT=/home/lfx/fitteia
PREFIX=
include libnumber.mk
# The core's version before 5.0.0: its library names get compatibility
# links to the current ones, so onefite-go/OneFit-Engine releases whose
# per-fit makefile still links -lonefit-4.0.4 keep working with this core.
LEGACY_LIBNUMBER=4.0.4
OS=LINUX
PERLCORE=/usr/lib/$(ARCH)-linux-gnu/perl/$(PERLVERSION)/CORE

.PHONY: install clean extensions extensions-selftest

install:
	make OS=$(OS) ROOT=$(ROOT) PERLCORE=$(PERLCORE) -C core/onefit-3.1 install-fitteia
	make OS=$(OS) ROOT=$(ROOT) PERLCORE=$(PERLCORE) -C core/onefit-3.1/perl install-pcop
	make OS=$(OS) ROOT=$(ROOT) PERLCORE=$(PERLCORE) -C core/onefit-3.1/doc install
	make OS=$(OS) ROOT=$(ROOT) PERLCORE=$(PERLCORE) -C local install
	install -d $(ROOT)$(PREFIX)/etc
	printf '%s\n' '# Generated by onefite-c-code make install - do not edit.' 'LIBNUMBER := $(LIBNUMBER)' > $(ROOT)$(PREFIX)/etc/engine.mk
	@if [ "$(LIBNUMBER)" != "$(LEGACY_LIBNUMBER)" ]; then \
		for n in onefit onefit-util onefit-modelos; do \
			ln -sf lib$$n-$(LIBNUMBER).a $(ROOT)$(PREFIX)/lib/lib$$n-$(LEGACY_LIBNUMBER).a; \
		done; \
		echo "===> linked the $(LEGACY_LIBNUMBER) library names to $(LIBNUMBER) for older onefite-go/OneFit-Engine releases"; \
	fi

clean:
	rm -f *~
	make ROOT=$(ROOT) -C core/onefit-3.1 clean
	make ROOT=$(ROOT) -C local clean

# Build and register everything in extensions/<name>/ (see extensions/README.md).
# Writes $(ROOT)/etc/extensions.mk and META-CATALOG.json; TEST=1 also runs each
# extension's own tests.
extensions:
	perl tools/extensions.pl install --c-root . --root $(ROOT)$(PREFIX) $(if $(TEST),--test)

extensions-selftest:
	perl tools/test_extensions.t
